apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-pipeline-samples
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: python-pipeline-samples
  template:
    metadata:
      labels:
        app: python-pipeline-samples
    spec:
      containers:
      - image: hamzazizi/python-pipeline-samples:2
        name: python-pipeline-samples
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: python-pipeline-samples
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: python-pipeline-samples
